---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= Configurazione e dispositivi supportati
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Questa domanda frequente risponde alle domande più frequenti sulla configurazione Cloud Insights e sui dispositivi supportati.



== Cloud Insights apporta modifiche al mio ambiente?

No Cloud Insights è uno strumento di sola lettura che raccoglie informazioni sull'ambiente. Cloud Insights non apporta mai modifiche alle risorse o alle configurazioni.



== Quale livello di autorizzazione richiede Cloud Insights ai miei dispositivi?

Nella maggior parte dei casi in cui il dispositivo lo supporta, è necessario un accesso di sola lettura. Alcune soluzioni non consentono l'accesso in sola lettura e richiedono pertanto le autorizzazioni elevate appropriate.



== Con quale frequenza Cloud Insights raccoglie informazioni?

In genere, Cloud Insights raccoglie i dati sulle performance ogni 5 minuti e scopre ogni ½ ora costrutti logici e fisici Cloud Insights imposta gli intervalli di polling predefiniti in base alle Best practice e alla scalabilità suggerite, ma consente all'utente di avere il controllo completo su questi intervalli.



== Qual è l'impatto di Cloud Insights sul mio ambiente?

Le comunicazioni IP senza agenti, out-of-band e passive di Cloud Insights contribuiscono a ridurre al minimo l'installazione, la manutenzione e l'impatto sull'ecosistema del data center. Il team di sviluppo delle performance di Cloud Insights adotta misure eccezionali per ridurre al minimo l'impatto sulle performance del data center nelle attività di monitoraggio delle performance stesse. L'impatto è considerato trascurabile nei normali ambienti operativi e può essere rilassato o inasprito nelle piattaforme tecnologiche altamente utilizzate o con performance inferiori. Per ulteriori informazioni, consultare la Guida all'installazione di Cloud Insights.



== Come posso elencare tutti gli host/VM in Cloud Insights?

Il complemento di widget e possibilità di query di Cloud Insights può essere utilizzato per fornire elenchi di stili di inventario per le risorse del data center. È possibile rendere disponibili elenchi di macchine virtuali fino agli spindle e numerosi costrutti per query, widget, dashboard e report di data warehouse e accedere tramite l'API RESTful.



== Cloud Insights offre lo stesso tipo di supporto per gli host non hypervisor correlati (ad esempio server fisici)?

Gli hypervisor come VMware forniscono informazioni dettagliate sugli host ESXI e sulle macchine virtuali (VM). Per i server fisici, Cloud Insights raccoglie le metriche fino all'HBA host. Cloud Insights utilizza un metodo unico per rilevare i server fisici utilizzando una tecnologia in attesa di brevetto. Una volta rilevato lo storage e/o gli switch, i nomi host dei server fisici sono contenuti nelle informazioni alias del fabric. Cloud Insights seleziona questi nomi host, li confronta in DNS e porta automaticamente gli host in Cloud Insights. Questa tecnica riduce notevolmente la necessità di aggiornamenti manuali dell'immissione e manutenzione dell'inventario degli strumenti.



== Cloud Insights fornisce la stessa profondità metrica del dispositivo (parità) in ambienti eterogenei?

Esistono diversi livelli di standardizzazione, compatibilità e nomenclatura per le piattaforme di terze parti e le tecnologie dei vendor. Cloud Insights tenta di normalizzare le informazioni su capacità e performance in un framework coerente. Alcune metriche di capacità e performance sono fornite in modo nativo dai contatori del dispositivo, come gli IOPS, la latenza e la capacità raw. Quando i contatori non sono forniti, Cloud Insights può tentare di riepilogare i valori (ad esempio, totalizzando gli IOPS o le capacità dei volumi sottostanti) e, nei casi in cui non siano disponibili, Cloud Insights tenterà di derivare i valori metrici attraverso vari algoritmi di calcolo. Cloud Insights offre una funzionalità di integrazione SNMP generica per incorporare metriche aggiuntive non attualmente raccolte da Cloud Insights.



== Cloud Insights supporta gli switch Fibre Channel?

Sì, oltre alla raccolta dei dati dalle risorse storage, Cloud Insights acquisisce anche i dati di inventario e performance dagli switch Cisco, Brocade e QLogic del tuo ambiente.



== Sono disponibili viste topopologie dell'intera infrastruttura? Cloud Insights mostra una "visibilità end-to-end"?

Sì, Cloud Insights rileva e mappa dinamicamente i costrutti logici e fisici, fornendo una vista topologia end-to-end interattiva di calcolo, fabric, virtualizzatori e storage back-end. Le icone della topologia consentono di accedere rapidamente alle risorse interessate e di identificare i carichi di lavoro e le violazioni negli ambienti di storage condivisi.
