---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Cloud Insights supporta Telegraf come agente per la raccolta di dati di integrazione su Kubernetes. 
---
= Prima di installare o aggiornare l'operatore di monitoraggio NetApp Kubernetes
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Leggere queste informazioni prima di installare o aggiornare link:task_config_telegraf_agent_k8s.html["Operatore di monitoring Kubernetes"].



=== Prerequisiti:

|===
| Componente | Requisito 


| Versione di Kubernetes | Kubernetes v1,20 e versioni successive. 


| Distribuzioni Kubernetes | Servizio Kubernetes elastico AWS (EKS)
Servizio Azure Kubernetes (AKS)
Google Kubernetes Engine (GKE)
Red Hat OpenShift
Rancher Kubernetes Engine (RKE)
VMware Tanzu 


| OS Linux | Cloud Insights non supporta i nodi in esecuzione con l'architettura Arm64.

Monitoraggio della rete: Deve essere in esecuzione Linux kernel versione 4.18.0 o superiore. Il sistema operativo Photon non è supportato. 


| Etichette | Cloud Insights supporta il monitoraggio dei nodi Kubernetes che eseguono Linux, specificando un selettore di nodi Kubernetes che cerca le seguenti etichette Kubernetes su queste piattaforme:

Kubernetes v1,20 e versioni successive: Kubernetes.io/os = linux
Rancher + Cattle.io come piattaforma di orchestrazione/Kubernetes: Cattle.io/os = linux 


| Comandi | I comandi curl e kubectl devono essere disponibili.; per ottenere i migliori risultati, aggiungere questi comandi al PERCORSO. 


| Connettività | Kubectl cli è configurato per comunicare con il cluster K8s di destinazione e per disporre di connettività Internet al vostro ambiente Cloud Insights.

Se si è dietro un proxy durante l'installazione, seguire le istruzioni nella link:/task_config_telegraf_agent_k8s.html#configuring-proxy-support["Configurazione del supporto proxy"] Sezione dell'installazione dell'operatore.

Per un controllo accurato e la refertazione dei dati, sincronizzare l'ora sul computer dell'agente utilizzando il protocollo NTP (Network Time Protocol) o SNTP (Simple Network Time Protocol). 


| Altro | Se si utilizza OpenShift 4,6 o versione successiva, è necessario seguire il link:task_config_telegraf_Agent_k8s.html#openshift-instructions[istruzioni OpenShift oltre a garantire che questi prerequisiti siano soddisfatti. 


| Token API | Se si sta ridistribuendo l'operatore (ad esempio se lo si sta aggiornando o sostituendo), non è necessario creare un nuovo token API; è possibile riutilizzare il token precedente. 
|===


=== Configurazione dell'operatore

Nelle versioni più recenti dell'operatore, le impostazioni modificate più comunemente possono essere configurate nella risorsa personalizzata _AgentConfiguration_. È possibile modificare questa risorsa prima di implementare l'operatore modificando il file _operator-config.yaml_. Questo file include esempi commentati di alcune impostazioni. Vedere l'elenco di link:telegraf_agent_k8s_config_options.html["impostazioni disponibili"] per la versione più recente dell'operatore.

È inoltre possibile modificare questa risorsa dopo che l'operatore è stato distribuito utilizzando il seguente comando:

 kubectl -n netapp-monitoring edit AgentConfiguration
Per determinare se la versione implementata dell'operatore supporta AgentConfiguration, eseguire il seguente comando:

 kubectl get crd agentconfigurations.monitoring.netapp.com
Se viene visualizzato il messaggio "Error from server (notfound)" (errore dal server (non trovato)), l'operatore deve essere aggiornato prima di poter utilizzare AgentConfiguration.



=== Tolerazioni e contamini

I DaemonSet _netapp-ci-telegraf-ds_, _netapp-ci-fluent-bit-ds_ e _netapp-ci-net-observer-L4-ds_ devono pianificare un pod su ogni nodo del cluster per raccogliere correttamente i dati su tutti i nodi. L'operatore è stato configurato in modo da tollerare alcuni *segni* noti. Se sono stati configurati dei tipi di contamini personalizzati sui nodi, impedendo l'esecuzione dei pod su ogni nodo, è possibile creare una *tolleranza* per tali tipi di contamini link:telegraf_agent_k8s_config_options.html["In _AgentConfiguration_"]. Se sono stati applicati dei tipi di manutenzione personalizzati a tutti i nodi del cluster, è necessario aggiungere anche le tolleranze necessarie all'implementazione dell'operatore per consentire la pianificazione e l'esecuzione del pod operatore.

Scopri di più su Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["Contamini e pedaggi"].

Tornare al link:task_config_telegraf_agent_k8s.html["*Pagina Installazione dell'operatore di monitoraggio NetApp Kubernetes*"]
