---
sidebar: sidebar 
permalink: task_dc_openstack.html 
keywords: data collector, openstack, OpenStack 
summary: Data collector OpenStack. 
---
= Data collector OpenStack
:allow-uri-read: 


[role="lead"]
Il data collector OpenStack (REST API / KVM) acquisisce i dati di inventario per tutte le istanze di OpenStack e, facoltativamente, i dati sulle performance delle macchine virtuali.



== Requisiti

* Indirizzo IP del controller OpenStack
* Credenziali del ruolo di amministratore di OpenStack e accesso sicuro all'hypervisor KVM Linux. Se non si utilizza l'account admin o privilegi equivalenti, sarà necessario utilizzare la versione di prova e gli errori per identificare le policy predefinite per rendere più semplice l'ID utente del data collector.
* Il modulo OpenStack Ceilometer deve essere installato e configurato per la raccolta delle performance. La configurazione del Ceilometer viene eseguita modificando il file nova.conf per ciascun hypervisor e riavviando il servizio Nova Compute su ciascun hypervisor. Il nome dell'opzione cambia per le diverse versioni di OpenStack:
+
** Icehouse
** Juno
** Chilo
** Libertà
** Mitaka
** Newton
** Ocata


* Per le statistiche CPU, "compute_monitors=ComputeDriverCPUMonitor" deve essere attivato in /etc/nova/nova.conf sui nodi di calcolo.
* Requisiti delle porte:
+
** 5000 per http e 13000 per https, per il servizio Keystone
** 22 per KVM SSH
** 8774 per Nova Compute Service
** 8776 per Cinder Block Service
** 8777 per Ceilometer Performance Service
** 9292 per Glance Image Service *Nota* la porta si collega al servizio specifico e il servizio può essere eseguito sul controller o su un altro host in ambienti più grandi.






== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Indirizzo IP controller OpenStack | Indirizzo IP o nome di dominio completo del controller OpenStack 


| Amministratore di OpenStack | Nome utente di un amministratore OpenStack 


| Password OpenStack | Password utilizzata per OpenStack Admin 


| Tenant amministratore OpenStack | Nome tenant amministratore OpenStack 


| Utente KVM sudo | Nome utente di KVM sudo 


| Scegliere 'Password' o 'OpenSSH Key file' per specificare il tipo di credenziale | Tipo di credenziale utilizzato per la connessione al dispositivo tramite SSH 


| Percorso completo alla chiave privata di inventario | Percorso completo alla chiave privata di inventario 


| Password KVM sudo | Password KVM sudo 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Abilita il rilevamento dell'inventario dell'hypervisor tramite SSH | Selezionare questa opzione per abilitare il rilevamento dell'inventario dell'hypervisor tramite SSH 


| Porta URL OpenStack Admin | Porta URL OpenStack Admin 


| Utilizzare HTTPS | Selezionare per utilizzare HTTP sicuro 


| Porta SSH | Porta utilizzata per SSH 


| Tentativi di processo SSH | Numero di tentativi di inventario 


| Intervallo polling inventario (min) | Intervallo tra i sondaggi di inventario. L'impostazione predefinita è 20 minuti. 
|===


== Risoluzione dei problemi

Alcune operazioni da eseguire in caso di problemi con questo data collector:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova: 


| "Errore di configurazione" con messaggi di errore che iniziano con "la policy non consente" o "non sei autorizzato" | * Controllare l'indirizzo ip * controllare il nome utente e la password 
|===
Per ulteriori informazioni, consultare link:concept_requesting_support.html["Supporto"] o in link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice di supporto Data Collector"].
