---
sidebar: sidebar 
permalink: task_troubleshooting_general_problems.html 
summary: Suggerimenti generali per la risoluzione dei problemi di Cloud Insights. 
keywords: troubleshooting, problems, browser, login, log in, accessing, access to, Trident, qtree, quota 
---
= Risoluzione dei problemi generali di Cloud Insights
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Qui troverai suggerimenti per la risoluzione dei problemi di Cloud Insights.

Vedere anche link:task_troubleshooting_linux_acquisition_unit_problems.html["Risoluzione dei problemi relativi all'unità di acquisizione Linux"] e. link:task_troubleshooting_windows_acquisition_unit_problems.html["Risoluzione dei problemi relativi all'unità di acquisizione di Windows"].



== Problemi di accesso

|===
| *Problema:* | *Provare questo:* 


| Cloud Insights si disconnette ogni 5 minuti | 396149d67edd166e53b49c38f4b707ba 


| e4ff2e59dd571d2bbd5a906b6fad2546 | a9a216fbb1fb9d774e7cedfcf74c00cf 


| Ho ricevuto un invito a Cloud Insights ma ricevo un messaggio "non autorizzato". | 199017f1d912993f091b6b969d3442ad 


| 176f8c6fa466059df49f2717c021d306 | 7a8624fb56224e907698f45ef2e4cc47 


| Sono stato disconnesso automaticamente dopo diversi giorni. | ed6e79e2f9b9c201ed834c6efeb7f356 


| Viene visualizzato il messaggio di errore "non più autorizzato all'accesso". | acf29dcaa06698c29122cba5402e3145 


| Altri errori di accesso | Provare la modalità incognito in Chrome o cancellare la cronologia del browser, i cookie e la cache. Provare con un profilo del browser diverso (ad esempio Chrome - Aggiungi persona). 
|===


== Altri problemi

|===


| *Domanda:* | *Risposta:* 


| Le mie quote rigide Qtree vengono visualizzate correttamente nelle query, ma le mie quote morbide vengono visualizzate come capacità totale del volume. È corretto? | Solo le quote rigide, impostate manualmente o tramite Trident, verranno visualizzate come quote impostate; se non vengono specificate quote rigide, la capacità Qtree sarà la capacità del volume interno. 


| Ho impostato manualmente una quota soft e una hard nello stesso Qtree, ma la capacità totale indicata è la quota hard; è corretto? | Sì, se viene specificata una quota rigida, questa verrà visualizzata come capacità totale. 


| Quando si inserisce un tempo di pianificazione del rapporto Cognos, a volte mi ritrovo con una "m" extra nel tempo di programmazione. Ad esempio, se si immette l'ora come "02:15 PM", è possibile aggiungere un carattere extra: "02:15 PMM" (o PMM). Quando clicco all'esterno, lo cambia in "2:15:00 AM".

È possibile salvare il report, ma quando si riapre il report salvato, l'ora pianificata viene visualizzata come AM (ad esempio, mattina), indipendentemente dal fatto che sia stato inserito AM o PM nell'ora pianificata. | Immettere nuovamente l'ora di programmazione, facendo attenzione a non inserire i caratteri "AM" o "PM" completi; è sufficiente digitare "A" per "AM o "P" per "PM". Se non viene visualizzato il carattere extra, l'ora di programmazione verrà impostata correttamente. 
|===


== Risorse

Ulteriori suggerimenti per la risoluzione dei problemi sono disponibili nella link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights["Knowledge base di NetApp"] (è richiesto l'accesso al supporto).

Ulteriori informazioni di supporto sono disponibili sul sito Cloud Insights link:concept_requesting_support.html["Supporto"] pagina.

Se disponi di un abbonamento Cloud Insights attivo, puoi utilizzare le seguenti opzioni di supporto:

link:https://www.netapp.com/us/contact-us/support.aspx["Telefono"]
link:https://mysupport.netapp.com/site/cases/mine/create?serialNumber=95001014387268156333["Ticket di supporto"]

Per ulteriori informazioni, consultare https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html["Documentazione di supporto Cloud Insights"].
