---
sidebar: sidebar 
permalink: task_dc_emc_unity.html 
keywords: data collector, VNXe, EMC, Unity 
summary: Configurazione del data collector VNXe. 
---
= Configurazione del data collector EMC Unity
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
IL data collector DELL EMC Unity (precedentemente noto come VNXe) fornisce il supporto dell'inventario per gli array di storage unificati VNXe. Cloud Insights attualmente supporta i protocolli iSCSI e NAS.



== Requisiti

* Unity data Collector è basato su CLI; è necessario installare Unisphere for Unity CLI (uemcli.exe) sull'unità di acquisizione in cui risiede il data collector VNXe.
* uemcli.exe utilizza HTTPS come protocollo di trasporto, pertanto l'unità di acquisizione deve essere in grado di avviare connessioni HTTPS con l'unità.
* Indirizzo IP o nome di dominio completo del dispositivo Unity
* È necessario disporre di almeno un utente di sola lettura per l'utilizzo da parte del data collector.
* HTTPS sulla porta 443 è obbligatorio
* Il data collector EMC Unity fornisce supporto NAS e iSCSI per l'inventario; verranno rilevati volumi Fibre Channel, ma Cloud Insights non esegue report su mappatura FC, mascheratura o porte di storage.




== Terminologia

Cloud Insights acquisisce le seguenti informazioni di inventario dal data collector Unity. Per ogni tipo di risorsa acquisita da Cloud Insights, viene mostrata la terminologia più comune utilizzata per questa risorsa. Durante la visualizzazione o la risoluzione dei problemi di questo data collector, tenere presente la seguente terminologia:

[cols="2*"]
|===
| Vendor/modello | Termine Cloud Insights 


| Disco | Disco 


| Array di storage | Storage 


| Del processore | Nodo di storage 


| Pool di storage | Pool di storage 


| Informazioni generali sul blocco iSCSI, VMware VMFS | Condividere 


| Sistema remoto di replica | Sincronizzazione 


| Nodo iSCSI | Nodo di destinazione iSCSI 


| ISCSI Initiator | ISCSI Target Initiator 
|===
Nota: Si tratta solo di mappature terminologiche comuni e potrebbero non rappresentare tutti i casi per questa origine dati.



== Configurazione

[cols="2*"]
|===
| Campo | Descrizione 


| Storage unificato | Indirizzo IP o nome di dominio completo del dispositivo Unity 


| Nome utente | Nome utente del dispositivo Unity 


| Password | Password per il dispositivo Unity 


| Percorso completo all'UEMCLI eseguibile | Percorso completo della cartella contenente l'eseguibile _uemcli.exe_ 
|===


== Configurazione avanzata

[cols="2*"]
|===
| Campo | Descrizione 


| Intervallo polling inventario (min) | Intervallo tra i sondaggi di inventario. L'impostazione predefinita è 40 minuti 


| Porta CLI Unity | Porta utilizzata per l'unità CLI 


| Intervallo di polling delle performance (sec) | Il valore predefinito è 300. 
|===


== Risoluzione dei problemi

Alcune operazioni da eseguire in caso di problemi con questo data collector:



=== Inventario

[cols="2*"]
|===
| Problema: | Prova: 


| "Impossibile eseguire l'utility esterna" con il messaggio di errore "Impossibile trovare l'eseguibile Unisphere uemcli" | * Verificare l'indirizzo IP, il nome utente e la password corretti * verificare che l'interfaccia CLI di Unisphere sia installata sull'unità di acquisizione Cloud Insights * verificare che la directory di installazione dell'interfaccia CLI di Unisphere sia corretta nella configurazione dell'origine dati * verificare che l'indirizzo IP dell'unità sia corretto nella configurazione dell'origine dati. Dall'unità di acquisizione Cloud Insights, aprire un CMD e passare alla directory di installazione configurata:{INSTALLDIR. Provare a stabilire una connessione con il dispositivo VNXe digitando: Uemcli -d <Your IP> -u <Your ID> /sys/General show 
|===
Per ulteriori informazioni, consultare link:concept_requesting_support.html["Supporto"] o in link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice di supporto Data Collector"].
