---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure 
summary: Workload Security utilizza i data colleator per raccogliere i dati di accesso ai file e agli utenti dai dispositivi. 
---
= Configurazione di Cloud Volumes ONTAP e Amazon FSX per NetApp ONTAP Collector
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security utilizza i data colleator per raccogliere i dati di accesso ai file e agli utenti dai dispositivi.



== Configurazione dello storage Cloud Volumes ONTAP

Consultare la documentazione di OnCommand Cloud Volumes ONTAP per configurare un'istanza di ha AWS a nodo singolo per ospitare l'agente di sicurezza del carico di lavoro:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[]

Una volta completata la configurazione, seguire la procedura per configurare SVM:https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== Piattaforme supportate

* Cloud Volumes ONTAP, supportato in tutti i provider di servizi cloud disponibili, ovunque sia disponibile. Ad esempio: Amazon, Azure, Google Cloud.
* ONTAP, Amazon FSX




== Configurazione del computer dell'agente

Il computer dell'agente deve essere configurato nelle rispettive subnet dei provider di servizi cloud. Per ulteriori informazioni sull'accesso alla rete, consultare [requisiti dell'agente].

Di seguito sono riportati i passaggi per l'installazione dell'agente in AWS. Per l'installazione, è possibile seguire procedure equivalenti, applicabili al provider di servizi cloud, in Azure o Google Cloud.

In AWS, attenersi alla seguente procedura per configurare il computer in modo che venga utilizzato come agente di sicurezza del carico di lavoro:

Per configurare il computer in modo che venga utilizzato come agente di sicurezza del carico di lavoro, procedere come segue:

.Fasi
. Accedere alla console AWS, accedere alla pagina EC2-Instances e selezionare _Launch instance_.
. Selezionare un file RHEL o CentOS AMI con la versione appropriata, come indicato in questa pagina:https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. Selezionare il VPC e la subnet in cui risiede l'istanza di Cloud ONTAP.
. Selezionare _t2.xlarge_ (4 vcpus e 16 GB di RAM) come risorse allocate.
+
.. Creare l'istanza EC2.


. Installare i pacchetti Linux richiesti utilizzando il gestore dei pacchetti YUM:
+
.. Installare _wget_ e _unzip_ pacchetti Linux nativi.






== Installare Workload Security Agent

. Accedere come Amministratore o Proprietario dell'account al proprio ambiente Data Infrastructure Insights.
. Accedere a sicurezza del carico di lavoro *Collectors* e fare clic sulla scheda *Agenti*.
. Fare clic su *+Agent* e specificare RHEL come piattaforma di destinazione.
. Copiare il comando Installazione agente.
. Incollare il comando Installazione agente nell'istanza RHEL EC2 a cui si è connessi. In questo modo viene installato l'agente workload Security, fornendo tutte le funzioni di link:concept_cs_agent_requirements.html["Prerequisiti dell'agente"] sono soddisfatti.


Per informazioni dettagliate, fare riferimento a questo link: https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== Risoluzione dei problemi

I problemi noti e le relative risoluzioni sono descritti nella seguente tabella.

|===


| Problema | Risoluzione 


| "Sicurezza del carico di lavoro: Impossibile determinare il tipo di ONTAP per il data collector Amazon FxSN" viene visualizzato dal Data Collector." Il cliente non riesce ad aggiungere il nuovo data collector Amazon FSxN in workload Security. La connessione al cluster FSxN sulla porta 443 dell'agente è in timeout. I gruppi di protezione firewall e AWS dispongono delle regole necessarie per consentire la comunicazione. Un agente è già implementato e si trova nello stesso account AWS. Lo stesso agente viene utilizzato per connettere e monitorare i dispositivi NetApp rimanenti (e tutti funzionano). | Risolvere questo problema aggiungendo il segmento di rete LIF fsxadmin alla regola di sicurezza dell'agente. Permesso a tutte le porte se non si è sicuri delle porte. 
|===